[package]
name = "counter"
version = "0.1.0"
authors = [
    "Kristoffer Ström <kristoffer@dusk.network>",
]
edition = "2021"

license = "MPL-2.0"

[dependencies]
dallo = { path = "../../dallo", default-features = false }

[lib]
crate-type = ["cdylib", "rlib"]

[workspace] # to keep out of main hatchery workspace
