[package]
name = "host"
version = "0.1.0"
authors = [
    "Eduardo Leegwater Simões <eduardo@dusk.network>",
]
edition = "2021"

license = "MPL-2.0"

[dependencies]
uplink = { path = "../../uplink", default-features = false }

[lib]
crate-type = ["cdylib", "rlib"]
