[package]
name = "hatchery"
version = "0.1.0"
edition = "2021"

license = "MPL-2.0"

[dependencies]
colored = "2.0.0"
rkyv = "0.7"
wasmer = { git = "https://github.com/dusk-network/dusk-wasmer", tag = "2.3.0-dusk" }
wasmer-vm = { git = "https://github.com/dusk-network/dusk-wasmer", tag = "2.3.0-dusk" }
dallo = { path = "../dallo" }
blake3 = "1.3.1"
parking_lot = "0.12.1"
tempfile = "3.2.0"
bsdiff = "0.1.6"
zstd = "0.9"
byteorder = "1.4.3"
