[package]
name = "hatchery"
version = "0.1.0"
edition = "2021"

license = "MPL-2.0"

[dependencies]
colored = "2.0.0"
rkyv = "0.7.38"
#wasmer = { git = "https://github.com/dusk-network/dusk-wasmer", branch = "vm2-wasmer-path-based" }
#wasmer-vm = { git = "https://github.com/dusk-network/dusk-wasmer", branch = "vm2-wasmer-path-based" }
wasmer = { path = "../../../rust/dusk-wasmer/lib/api" }
wasmer-vm = { path = "../../../rust/dusk-wasmer/lib/vm" }
dallo = { path = "../dallo", default-features = false }
blake3 = "1.3.1"
parking_lot = "0.12.1"
tempfile = "3.2.0"
