on:
  pull_request:
  push:
    branches:
      - main

name: build

jobs:
  analyze:
    name: Dusk analyzer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install latest nightly toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
      - name: Install cargo-dusk-analyzer
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: --git https://github.com/dusk-network/cargo-dusk-analyzer
      - name: Run `cargo dusk-analyzer`
        uses: actions-rs/cargo@v1
        with:
          command: dusk-analyzer
  test:
    name: Make test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install latest nightly toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
      - name: Install WASM target
        run: rustup target add wasm32-unknown-unknown
      - name: Add `rust-src` component
        run: rustup component add rust-src
      - name: Run `make test`
        run: make test

  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install latest nightly toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
      - run: rustup component add rustfmt
      - name: Run `cargo fmt`
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install latest nightly toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
      - run: rustup component add clippy
      - name: Run `cargo clippy`
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings
